services:
  mysql:
    image: mysql:8.4
    container_name: mysql-prod
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: userservice
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      retries: 10


  app:
    build:
      context: ./app
    container_name: user-service-app
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8000:8000"
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: userservice
      DB_USER: appuser
      DB_PASSWORD: apppassword

volumes:
  mysql_data:
